# Generated by Django 5.0.6 on 2024-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.IntegerField()),
                ('leitura_sensor', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cep', models.CharField(max_length=9)),
                ('distancia_sensor_solo', models.FloatField()),
                ('status_area', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
